import React from "react";
import "./globals.css";
import NavBar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<body className="min-h-screen flex flex-col">
    <header className="h-16">
      <NavBar/>
    </header>
    <main className="flex-grow flex">
      {children}
      </main>
</body>
    </html>
  );
}
